apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: ubuntu/apache2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3006



---


apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3006
   

